### ISSUE TITLE
Refactor IndexCommand.php

### ISSUE THREAD

**Issue by thomas-sc** [dikastes/liszt_bibliography#19]
It would be good if the command IndexCommand.php (branch upgrade-to-typo3-v13) was refactored.

- The function fetchCitationLocale often gets a error code 500 from the Zotero API. The error was handled in a try/catch block, where the exception was not interrupted, which can lead to an endless loop in case of permanent errors or offline API. Also it would be even better to find out why the 500 errors occur ;-)
- Perhaps it is better and more memory-efficient to retrieve the data in batches and store them one after the other in Elasticsearch?
- Some methods have try/catch blocks while others do not.
- prepare the process for autonomous execution and send errors to a log or to admin.

**Comment by dikastes** [comment]
Most of the above points have been resolved. What still remains is preparing the IndexCommand for autonomous execution.
